### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by GotJimmy** [snowkit/atom-haxe#42]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [haxe](https://github.com/snowkit/atom-haxe) package, v0.8.7
### Stack Trace

Uncaught Error: spawn EACCES

```
At child_process.js:1145

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at exports.spawn (child_process.js:977:9)
  at Object.module.exports.reset (/Users/cpg/.atom/packages/haxe/lib/completion/server.js:41:24)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "haxe": {
    "haxe_path": "/usr/lib/Haxe",
    "haxelib_path": "/usr/lib/Haxe/lib",
    "debug_logging": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.11
atom-material-ui, v0.5.21
flow, v0.4.2
haxe, v0.8.7
language-actionscript3, v0.3.0
language-haxe, v0.3.0
lime, v0.3.1
linter, v1.4.2

# Dev
No dev packages
```

**Comment by mnolin** [comment]
I'm getting this error as well on startup, trying to get things setup to so I can build from atom correctly. I can run a build via the command line appropriately with the following command `flow run web`

## Stack Trace

internal/child_process.js:298

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:351:9)
    at Object.module.exports.reset (/Users/mattnolin/.atom/packages/haxe/lib/completion/server.js:41:24) 

## My setup is:

Atom version: 1.3.2
Mac OS: 10.11.2
Package: haxe (0.8.10)

## Config

Haxe path: "/usr/local/lib/haxe"
Haxelib executable path: "/usr/local/lib/haxe/lib"

## Installed Packages
- flow
- haxe
- language-haxe
- linter

**Comment by jeremyfa** [comment]
Seems that atom doesn't have the permissions to execute your haxe binary. Do you have anything custom in your haxe installation?

**Comment by mnolin** [comment]
The only thing is the path, when I tried to run haxelib setup to the default location it said it didn't have permission so I think that might be the actual issue. haxelib seems to be able to run fine but is installed to /usr/local/lib/haxelib

Maybe related to this? https://github.com/HaxeFoundation/haxe/issues/4483

I installed haxe with the default Mac OS X Installer from http://haxe.org/download/ which mentions the above thread "Make sure to check the changelog. In particular, this release fixes installation issues on OS X 10.11 'El Capitan', alongside with some C++, Java, C# and JS bug fixes."

That's why in the settings I tried to specify the paths mentioned in the above Config. I also tried "usr/local/lib/haxelib" for the Haxelib executable path but it doesn't seem to make a difference.
