### ISSUE TITLE
Failed to load the haxe package

### ISSUE THREAD

**Issue by autonomnom** [snowkit/atom-haxe#44]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.18
**System**: MUMLA
**Thrown From**: [haxe](https://github.com/snowkit/atom-haxe) package, v0.8.7
### Stack Trace

Failed to load the haxe package

```
At Cannot find module 'atom-message-panel'

Error: Cannot find module 'atom-message-panel'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Mümla\.atom\packages\haxe\lib\utils\log.js:3:25)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Mümla\.atom\packages\haxe\lib\haxe-state.js:5:13)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Mümla\.atom\packages\haxe\lib\completion\query.js:7:15)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Mümla\.atom\packages\haxe\lib\haxe.js:4:20)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package.js:761:34)
  at C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package.js:192:28
  at Package.module.exports.Package.measure (C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.load (C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package.js:183:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\src\package-manager.js:485:30)
  at C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\node_modules\settings-view\lib\package-manager.js:371:29
  at exit (C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Mümla\AppData\Local\atom\app-1.0.18\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```
### Commands

```
     -2:07.7.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
haxe, v0.8.7

# Dev
No dev packages
```

**Comment by ruby0x1** [comment]
Did you get by? It seems that this is a misconfiguration from atom itself, it looks as if it hasn't downloaded the plugin dependencies from `apm`.
