### ISSUE TITLE
Uncaught TypeError: treeview.serialize is not a function

### ISSUE THREAD

**Issue by Hodes** [snowkit/atom-haxe#68]
[Enter steps to reproduce:]

1. Have a project with a build.hxml on project root directory
2. Try to right click and set the .hxml as active HXML build file

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [haxe](https://github.com/snowkit/atom-haxe) package 0.8.14

### Stack Trace

Uncaught TypeError: treeview.serialize is not a function

```
At /Users/hodes/.atom/packages/haxe/lib/haxe.js:133

TypeError: treeview.serialize is not a function
    at Object.set_hxml_file_from_treeview (/packages/haxe/lib/haxe.js:133:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1292:1)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -5:32.8.0 core:backspace (input.hidden-input)
  6x -5:32.1.0 core:select-right (input.hidden-input)
     -5:29.6.0 core:save (input.hidden-input)
  6x -5:24 haxe:build (input.hidden-input)
     -5:16.6.0 tree-view:collapse-directory (div.tool-panel.tree-view)
 10x -5:15.8.0 haxe:build (input.hidden-input)
     -1:41.9.0 haxe:set-hxml-file (span.name.icon.icon-file-text)
     -0:36.7.0 core:backspace (input.hidden-input)
     -0:36.5.0 core:confirm (input.hidden-input)
     -0:26.3.0 haxe:set-hxml-file (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-typescript 11.0.3 
build-cmake 0.9.1 
busy-signal 1.4.1 
haxe 0.8.14 
intentions 1.1.2 
language-cmake 0.3.0 
language-haxe 0.6.0 
linter 2.1.4 
linter-ui-default 1.4.0 
```

**Comment by supergeoff** [comment]
Hello,
I have the same issue:

Mac OS: 10.13.4
Haxe package: 0.8.14
Atom: 1.27.1 x64

Can someone explain how to update the plugin based on the latest git version?

Thank you.

Regards;
