### ISSUE TITLE
Failed to activate the haxe package

### ISSUE THREAD

**Issue by nanocat-net** [snowkit/atom-haxe#74]
1. Open Atom
2. Observe error :-)

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [haxe](https://github.com/snowkit/atom-haxe) package 0.8.14

### Stack Trace

Failed to activate the haxe package

```
At primordials is not defined

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/packages/haxe/node_modules/natives/index.js:143:24)
    at /packages/haxe/node_modules/natives/index.js:55:10)
    at /packages/haxe/node_modules/graceful-fs/fs.js:1:192)
    at /packages/haxe/node_modules/graceful-fs/fs.js:3:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/haxe/node_modules/graceful-fs/graceful-fs.js:3:27)
    at /packages/haxe/node_modules/graceful-fs/graceful-fs.js:160:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/haxe/node_modules/fs-extra/lib/json.js:1:165)
    at /packages/haxe/node_modules/fs-extra/lib/json.js:33:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/haxe/node_modules/fs-extra/lib/index.js:2:12)
    at /packages/haxe/node_modules/fs-extra/lib/index.js:92:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete 0.47.0 
busy-signal 2.0.1 
haxe 0.8.14 
intentions 1.1.5 
lang-gdscript 6.0.0 
language-haxe 0.6.0 
linter 3.1.1 
linter-ui-default 2.1.4 
teletype 0.13.4 
```

**Comment by sepiatonal** [comment]
Me too

**Comment by insanity54** [comment]
I'm seeing this also. 

Atom    : 1.53.0
Electron: 6.1.12
OS: Pop!_OS 20.04 LTS
Thrown From: haxe package 0.8.14

### stack trace
```
primordials is not defined

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/chris/.atom/packages/haxe/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/chris/.atom/packages/haxe/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/chris/.atom/packages/haxe/node_modules/graceful-fs/fs.js:1:192)
    at Object.<anonymous> (/home/chris/.atom/packages/haxe/node_modules/graceful-fs/fs.js:3:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at Object.<anonymous> (/home/chris/.atom/packages/haxe/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Object.<anonymous> (/home/chris/.atom/packages/haxe/node_modules/graceful-fs/graceful-fs.js:160:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at Object.<anonymous> (/home/chris/.atom/packages/haxe/node_modules/fs-extra/lib/json.js:1:165)
    at Object.<anonymous> (/home/chris/.atom/packages/haxe/node_modules/fs-extra/lib/json.js:33:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at Object.<anonymous> (/home/chris/.atom/packages/haxe/node_modules/fs-extra/lib/index.js:2:12)
    at Object.<anonymous> (/home/chris/.atom/packages/haxe/node_modules/fs-extra/lib/index.js:92:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147498)
```

### non-core packages
```
├── atom-beautify@0.33.4
├── busy-signal@2.0.1
├── haxe@0.8.14
├── intentions@1.1.5
├── language-haxe@0.6.0
├── linter@3.1.1
├── linter-ui-default@2.1.5
├── markdown-preview@0.160.2
└── terminus@4.0.6
```

**Comment by jeremyfa** [comment]
Not providing any solution for the issue specifically, but note that this haxe package for atom is not really maintained anymore. If you want to get better haxe tooling, you may consider moving to Visual Studio Code with the more feature complete and actively maintained Haxe extension (https://github.com/vshaxe/vshaxe)

**Comment by nanocat-net** [comment]
Stale
